import '../styles/globals.css'
import { AppProps } from 'next/dist/next-server/lib/router/router'
import Head from 'next/head'


function MyApp({ Component, pageProps }: AppProps): JSX.Element {
    return <>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap"
              rel="stylesheet"/>
        <Component { ...pageProps } />
    </>

}

export default MyApp
